# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Karthik Kulkarni"
weight = 1

#[fr]
#languageName = "French"
#languagedirection = ""
#title = "kishan"
#weight = 2